### ISSUE TITLE
Two obfuscators detected - defuscate error

### ISSUE THREAD

**Issue by xFFFFF** [0xd4d/de4dot#157]
Detect output:
```
  1: Unknown
100: Agile.NET
  0: Babel .NET
  0: CodeFort
  0: CodeVeil
  0: CodeWall
Deobfuscating control flow: System.Void <Module>::.cctor() (06000001)
Deobfuscating control flow: System.Void <AgileDotNetRTPro>::Initialize() (060003F1)
Deobfuscating control flow: System.Void <AgileDotNetRTPro>::PostInitialize() (060003F2)
  0: Confuser
110: Crypto Obfuscator
Deobfuscating control flow: System.Void <Module>::.cctor() (06000001)
  0: DeepSea
  0: Dotfuscator
  0: .NET Reactor 3.x
  0: .NET Reactor 4.x
  0: Eazfuscator.NET
  0: Goliath.NET
  0: ILProtector
  0: MaxtoCode
  0: MPRESS
  0: Rummage
  0: Skater .NET
  0: SmartAssembly
  0: Spices.Net
  0: Xenocode
More than one obfuscator detected:
  CliSecure (use: -p an)
  Crypto Obfuscator (use: -p co)
Detected Crypto Obfuscator l)
```

Command `-p an`
Output:
```
ERROR: Stack trace:
ERROR:
ERROR: Server stack trace:
ERROR:    at System.Runtime.CompilerServices.RuntimeHelpers._RunModuleConstructor(RuntimeModule module)
ERROR:    at de4dot.mdecrypt.DynamicMethodsDecrypter.LoadObfuscator()
ERROR:    at AssemblyData.MethodDecrypterService.LoadObfuscator(String filename)
ERROR:    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
ERROR:    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
ERROR:
ERROR: Exception rethrown at [0]:
ERROR:    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
ERROR:    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
ERROR:    at AssemblyData.IMethodDecrypterService.LoadObfuscator(String filename)
ERROR:    at de4dot.code.deobfuscators.MethodsDecrypter.Decrypt2(ServerClrVersion serverVersion, String filename, Byte[] moduleCctorBytes)
ERROR:    at de4dot.code.deobfuscators.MethodsDecrypter.Decrypt(ServerClrVersion serverVersion, String filename, Byte[] moduleCctorBytes)
ERROR:    at de4dot.code.deobfuscators.Agile_NET.MethodsDecrypter.Decrypt(MyPEImage peImage, ModuleDefMD module, CliSecureRtType csRtType, DumpedMetho
ds& dumpedMethods)
ERROR:    at de4dot.code.deobfuscators.Agile_NET.Deobfuscator.GetDecryptedModule(Int32 count, Byte[]& newFileData, DumpedMethods& dumpedMethods)
ERROR:    at de4dot.code.ObfuscatedFile.Deobfuscate()
ERROR:    at de4dot.cui.FilesDeobfuscator.DeobfuscateAllFiles(IEnumerable`1 allFiles)
ERROR:    at de4dot.cui.FilesDeobfuscator.DeobfuscateAll()
ERROR:    at de4dot.cui.Program.Main(String[] args)
ERROR:
ERROR:
ERROR: Caught an exception:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Message:
ERROR:   The type initializer for '<Module>' threw an exception.
ERROR: Type:
ERROR:   System.TypeInitializationException
ERROR: ------------------------------------------------------------------------------
```

Command `-p co` output:
```
Adding string decrypter. Resource: "XA90A13B49D1FF775AAC10FB801E971A2"
WARNING: Found unknown resource encryption flags: 0x0A
ERROR:
ERROR:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Stack trace:
ERROR:    at System.IO.Compression.Inflater.DecodeUncompressedBlock(Boolean& end_of_block)
ERROR:    at System.IO.Compression.Inflater.Decode()
ERROR:    at System.IO.Compression.Inflater.Inflate(Byte[] bytes, Int32 offset, Int32 length)
ERROR:    at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
ERROR:    at de4dot.code.deobfuscators.CryptoObfuscator.ResourceDecrypter.Decrypt(Stream resourceStream)
ERROR:    at de4dot.code.deobfuscators.CryptoObfuscator.StringDecrypter.Initialize(ResourceDecrypter resourceDecrypter)
ERROR:    at de4dot.code.deobfuscators.CryptoObfuscator.Deobfuscator.DeobfuscateBegin()
ERROR:    at de4dot.code.ObfuscatedFile.Deobfuscate()
ERROR:    at de4dot.cui.FilesDeobfuscator.DeobfuscateAllFiles(IEnumerable`1 allFiles)
ERROR:    at de4dot.cui.FilesDeobfuscator.DeobfuscateAll()
ERROR:    at de4dot.cui.Program.Main(String[] args)
ERROR:
ERROR:
ERROR: Caught an exception:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Message:
ERROR:   Block length does not match with its complement.
ERROR: Type:
ERROR:   System.IO.InvalidDataException
```

**Comment by dnvthv** [comment]
Still not working CryptoObfuscator latest version.

**Comment by stosea** [comment]
Hi @cc66 ,
Change as your comment is working, but the file cleaned have problem with functions.
I can't read exactly funtion because it reference from Declare and no content
![image](https://user-images.githubusercontent.com/44799333/48050652-0b612680-e1d5-11e8-80be-cb8ead4a4a52.png)
![image](https://user-images.githubusercontent.com/44799333/48050761-7579cb80-e1d5-11e8-8f41-43126a82868f.png)

**Comment by dnvthv** [comment]
Hi @cc66
Can you check this target?

[test.zip](https://github.com/0xd4d/de4dot/files/2553928/test.zip)
