### ISSUE TITLE
IPC-Port error: pipe ended

### ISSUE THREAD

**Issue by toxicphreAK** [0xd4d/de4dot#171]
The stack trace is the following:
```
ERROR: ------------------------------------------------------------------------------
ERROR: Stack trace:
ERROR: 
ERROR: Server stack trace: 
ERROR:    at System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length)
ERROR:    at System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
ERROR:    at System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
ERROR:    at System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
ERROR:    at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
ERROR:    at System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
ERROR:    at System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders()
ERROR:    atSystem.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
ERROR:    at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
ERROR: 
ERROR: Exception rethrown at [0]: 
ERROR:    at de4dot.code.deobfuscators.MethodsDecrypter.Decrypt(ServerClrVersion serverVersion, String filename, Byte[] moduleCctorBytes)
ERROR:    at de4dot.code.deobfuscators.MethodsDecrypter.Decrypt(ModuleDef module, Byte[] moduleCctorBytes)
ERROR:    at de4dot.code.deobfuscators.Agile_NET.MethodsDecrypter.Decrypt(MyPEImage peImage, ModuleDefMD module, CliSecureRtType csRtType, DumpedMethods& dumpedMethods)
ERROR:    at de4dot.code.deobfuscators.Agile_NET.Deobfuscator.GetDecryptedModule(Int32 count, Byte[]& newFileData, DumpedMethods& dumpedMethods)
ERROR:    at de4dot.code.ObfuscatedFile.Deobfuscate()
ERROR:    at de4dot.cui.FilesDeobfuscator.DeobfuscateAllFiles(IEnumerable`1 allFiles)
ERROR:    at de4dot.cui.FilesDeobfuscator.DeobfuscateAll()
ERROR:    at de4dot.cui.FilesDeobfuscator.DoIt()
ERROR:    at de4dot.cui.Program.Main(String[] args)
```

seems to be issued by the 5 callings of Decrypt2 in `de4dot.code.deobfuscators:MethodDecrypter:Decrypt(ServerClrVersion serverVersion, string filename, byte[] moduleCctorBytes)`.

Don't understand, why this is looped 5 times and sometimes it runs (about every 10 to 20 times)?

**Comment by 0xd4d** [comment]
I've noticed it fail too but it's usually when all cores are very busy. Try again.
