### ISSUE TITLE
Error with crypto obfuscator

### ISSUE THREAD

**Issue by BenKnigge** [0xd4d/de4dot#188]
I have a file that is being detected as being obfuscated with both "Crypto obfuscator" and Confuser v1.9

I'm able to process the file once with the  -p cr flag

Afterwards if I detect the cleaned file I see only "crypto obfuscator" remaining.

When  try to clean the file with - p co and -v flag

I get the following error

ERROR: ------------------------------------------------------------------------------
ERROR: Stack trace:
ERROR: at de4dot.code.deobfuscators.CryptoObfuscator.CoUtils.DecryptResourceName(ModuleDefMD module, MethodDef method)
ERROR: at de4dot.code.deobfuscators.CryptoObfuscator.ConstantsDecrypter.Initialize(ResourceDecrypter resourceDecrypter)
ERROR: at de4dot.code.deobfuscators.CryptoObfuscator.Deobfuscator.DeobfuscateBegin()
ERROR: at de4dot.code.ObfuscatedFile.Deobfuscate()
ERROR: at de4dot.cui.FilesDeobfuscator.DeobfuscateAllFiles(IEnumerable`1 allFiles)
ERROR: at de4dot.cui.FilesDeobfuscator.DeobfuscateAll()
ERROR: at de4dot.cui.FilesDeobfuscator.DoIt()
ERROR: at de4dot.cui.Program.Main(String[] args)
ERROR:
ERROR:
ERROR: Caught an exception:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Message:
ERROR: Object reference not set to an instance of an object.
ERROR: Type:
ERROR: System.NullReferenceException
ERROR: ------------------------------------------------------------------------------
ERROR:
ERROR: Try the latest version!

When I try to clean the app with the -p co flag as the first step I get an error "Unknown version"

**Comment by tualeomar** [comment]
D:\deDot\de4dot>de4dot-x64.exe d:\fe\fe.exe -vv -p co

de4dot v3.1.41592.3405 Copyright (C) 2011-2014 de4dot@gmail.com
Latest version and source code: https://github.com/0xd4d/de4dot
21 deobfuscator modules loaded!

Args:
  "d:\\fe\\fe.exe"
  "-vv"
  "-p"
  "co"
Detected Crypto Obfuscator (d:\fe\fe.exe)
Cleaning d:\fe\fe.exe
Deobfuscating control flow: System.Byte[] ?1?.?22?::?4?(System.Int64,System.IO.Stream) (0600011A)
Decrypting resources, name: "fe&"
  Adding decrypted resource "fe%"
  Adding decrypted resource "fe$"
  Adding decrypted resource "rpFt.rpt"
  Adding decrypted resource "A.\u0016.resources"
  Adding decrypted resource "demo.Resources.resources"
Deobfuscating control flow: System.Void ?1?.?28?::?2?() (06000134)
Static string decryption: System.Void ?1?.?28?::?2?() (06000134)
  Could not deobfuscate 06000134
ERROR:
ERROR:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Stack trace:
ERROR:    at de4dot.code.deobfuscators.CryptoObfuscator.ConstantsDecrypter.Initialize(ResourceDecrypter resourceDecrypter)
ERROR:    at de4dot.code.deobfuscators.CryptoObfuscator.Deobfuscator.DeobfuscateBegin()
ERROR:    at de4dot.code.ObfuscatedFile.Deobfuscate()
ERROR:    at de4dot.cui.FilesDeobfuscator.DeobfuscateAllFiles(IEnumerable`1 allFiles)
ERROR:    at de4dot.cui.FilesDeobfuscator.DeobfuscateAll()
ERROR:    at de4dot.cui.Program.Main(String[] args)
ERROR:
ERROR:
ERROR: Caught an exception:
ERROR:
ERROR: ------------------------------------------------------------------------------
ERROR: Message:
ERROR:   Object reference not set to an instance of an object.
ERROR: Type:
ERROR:   System.NullReferenceException
ERROR: ------------------------------------------------------------------------------
ERROR:
ERROR: Try the latest version!

**Comment by tualeomar** [comment]
this problem
![sc](https://user-images.githubusercontent.com/37269676/50716320-8325c300-1057-11e9-8146-979ff3ac33b6.png)
